name: Build C Project

on:
  schedule:
    - cron: '*/5 * * * *' # Menjalankan setiap 1 menit, sesuaikan dengan kebutuhan Anda.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Compile C code
      run: |
        make

    - name: List files (debugging)
      run: |
        ls -la

    - name: Upload artifact (output.exe)
      uses: actions/upload-artifact@v3
      with:
        name: output.exe
        path: output.exe

    - name: Commit and Push output.exe
      run: |
        # Konfigurasi git
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        # Pindahkan file output.exe ke direktori tertentu (opsional)
        mkdir -p build
        mv output.exe build/phishing.exe

        # Stage file output.exe
        git add build/phishing.exe

        # Commit perubahan
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-commit: Add compiled output.exe"
          git push
        fi
