name: Build C Project
on:
  schedule:
    - cron: '*/5 * * * *' # Menjalankan setiap 5 menit
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    # Langkah 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Langkah 2: Install Chocolatey
    - name: Install Chocolatey
      shell: pwsh
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
        Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    # Langkah 3: Install MinGW menggunakan Chocolatey
    - name: Install MinGW
      shell: pwsh
      run: |
        choco install mingw -y

    # Langkah 4: Set PATH untuk MinGW
    - name: Set PATH for MinGW
      shell: pwsh
      run: |
        echo "C:\tools\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    # Langkah 5: Kompilasi resource file
    - name: Compile resource file
      shell: pwsh
      run: |
        windres -i resource.rc -o resource.o
        if (Test-Path resource.o) {
          Write-Host "Resource file compiled successfully"
        } else {
          Write-Host "Resource file compilation failed"
          exit 1
        }

    # Langkah 6: Kompilasi program C
    - name: Compile C code
      shell: pwsh
      run: |
        gcc main.c resource.o -o phishing.exe -lm
        if (Test-Path phishing.exe) {
          Write-Host "phishing.exe created successfully"
        } else {
          Write-Host "Failed to create phishing.exe"
          exit 1
        }

    # Langkah 7: Install Resource Hacker
    - name: Install Resource Hacker
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "http://www.angusj.com/resourcehacker/resource_hacker.zip" -OutFile "reshacker.zip"
        Expand-Archive -Path "reshacker.zip" -DestinationPath "reshacker"

    # Langkah 10: Simpan output sebagai artifact
    - name: Create artifacts directory
      shell: pwsh
      run: |
        New-Item -Path "${{ github.workspace }}\artifacts" -ItemType Directory -Force
        Copy-Item -Path "phishing.exe" -Destination "${{ github.workspace }}\artifacts\" -Force

    # Langkah 11: Commit dan push file phishing.exe ke repositori
    - name: Commit and Push phishing.exe
      shell: pwsh
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        New-Item -Path "build" -ItemType Directory -Force
        Copy-Item -Path "phishing.exe" -Destination "build\phishing.exe" -Force
        git add build/phishing.exe
        $hasChanges = git diff --cached --quiet
        if ($LASTEXITCODE -ne 0) {
          git commit -m "Auto-commit: Add compiled phishing.exe"
          git push
        } else {
          Write-Host "No changes to commit"
        }
