name: Build C Project

on:
  schedule:
    - cron: '*/5 * * * *' # Menjalankan setiap 1 menit, sesuaikan dengan kebutuhan Anda.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Langkah 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Langkah 2: Install dependencies (compiler C)
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    # Langkah 3: Compile kode C
    - name: Compile C code
      run: |
        make

    # Langkah 4: Debugging - List files di direktori
    - name: List files (debugging)
      run: |
        ls -la

    # Langkah 5: Upload artifact (phishing.exe)
    - name: Upload artifact (phishing.exe)
      uses: actions/upload-artifact@v4
      with:
        name: phishing.exe
        path: phishing.exe

    # Langkah 6: Commit dan push file phishing.exe ke repositori
    - name: Commit and Push phishing.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Konfigurasi git
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        # Pindahkan file phishing.exe ke direktori tertentu (opsional)
        mkdir -p build
        mv phishing.exe build/phishing.exe

        # Stage file phishing.exe
        git add build/phishing.exe

        # Commit perubahan
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-commit: Add compiled phishing.exe"
          git push
        fi
